
<Menu>:
  orientation: 'vertical'
  Button:
    text: "Baby Snake"
    on_press: root.manager.current = 'Baby Snake'
  Button:
    text: "Child Snake"
    on_press: root.manager.current = 'Child Snake' 
  Button:
    text:"Teenager Snake"
    on_press: root.manager.current = 'Teenager Snake'
  Button:
    text: "Adult Snake"
    on_press: root.manager.current = 'Adult Snake' 
  Button:
    text: "Super Snake"
    on_press: root.manager.current = 'Super Snake'